### ISSUE TITLE
container的transition卡卡感觉

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#76]
## 问题描述

1. 了解container的transition动画效果实现思路？
2. 我感觉每次页面切换到最后有点卡卡感觉，我看scss，设置关键帧，想问有哪些相关参数，怎么调节？

**Comment by minwe** [comment]
- Android 上卡是正常现象，不卡才不正常，可以去掉 `transition` 属性关闭动画。
- 动画实现及方式编写参见文档：
   - https://facebook.github.io/react/docs/animation.html
   - http://t.amazeui.org/#/docs/container?_k=1p53ex

**Comment by fangjj** [comment]
嗯。android是有些卡，是什么原因造成的呢。我看scss代码有关键帧，是不是跟里面几个css类设置参数有关，另外transition都写到项目中了，现在一个个改，是不是不友好，希望提供全局配置开关。

**Comment by minwe** [comment]
上面说了，你要不想用动画就把 `transition` 属性去了。

想自己写动画就按照文档 http://t.amazeui.org/#/docs/container 「编写动画说明」 部分编写，然后把动画名称传进去就行了。目前由于资源限制，没有计划做更多选项。

**Comment by fangjj** [comment]
可能我没有描述清楚，目前项目使用transition动画，是参考按照文档 http://t.amazeui.org/#/docs/container 写的。transition出现在项目很多代码中，而且利用react-router动态更改了一个页面的transition，例如http://numwar.daoapp.io/setting（用户名：14963238982，密码：123456）进入设置页面的动画是sfr，然后点击设置页面链接到任何页面后，例如使用教程页面，点击返回，返回到设置页面，这是设置页面的transition就被改成了rfr。这种动画是参考qq的。现在遇到问题是，在android，切换快完成时候有些卡顿，我想自己写scss，覆盖你的动画样式，想了解一下你切换动画样式，是怎么写的。方便自己覆盖你的样式。

**Comment by minwe** [comment]
添加 `transition` 属性以后，Container 会调用 https://facebook.github.io/react/docs/animation.html 中的 `ReactCSSTransitionGroup` 插件，router 切换时，离开的组件上会依次添加 `.xxxx-leave`、`xxx-leave-active` className，进入的组件会依次添加  `.xxxx-enter`、`xxx-enter-active` className，通过在这些类名定义 CSS transition 或者 animation 实现动画效果。

Container 的 `transition` 属性应用到 CSSTransitionGroup 的 `transitionName` 属性上，不过加了个前缀，https://github.com/amazeui/amazeui-touch/blob/5c6fe2b0a322d47750b2f4719810ab2cb50fcc9c/js/Container.js#L128，所以编写样式时就变成下面这样了：

```css
/* 以编写名为 `fade` 的动画为例 */
.view-transition-fade-enter {
  opacity: 0.01;
}

.view-transition-fade-enter.view-transition-fade-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}

.view-transition-fade-leave {
  opacity: 1;
}

.view-transition-fade-leave.view-transition-fade-leave-active {
  opacity: 0.01;
  transition: opacity 300ms ease-in;
}
```

如果觉得前缀太长太麻烦了，你可以直接传 `transitionName` 进去覆盖掉。

你可以把 https://github.com/amazeui/amt-starter-kit/blob/master/app/js/App.js#L40-L42 这几行注释去掉，看看效果，动画定义在 https://github.com/amazeui/amt-starter-kit/blob/master/app/style/app.scss#L11-L28 中。


注意：

> 1.0.0-rc.1 有点小问题，需要手动删掉
> node_modules/amazeui-touch/scss/amazeui.touch.scss 中的 `$ratchicons-path: 'fonts/';` 这一行

不然打包会出错。
