### ISSUE TITLE
想问一下怎么更改touch里面组件的样式

### ISSUE THREAD

**Issue by wjdimba** [amazeui/amazeui-touch#78]
比如Accordion这个组件我想把箭头去掉

**Comment by minwe** [comment]
目前没有什么好的方法，只能找到对应的 className 以后覆写，如：

```css
.accordion-icon {
  display: none;
}
```
