### ISSUE TITLE
如何让tabbar 里面的list正常运作？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#82]
如下图，不能scroll了，即使多了很多内容
![image](https://cloud.githubusercontent.com/assets/12795428/16728599/e5ad3f14-4799-11e6-8c2b-22a0a7c28226.png)

**Comment by minwe** [comment]
```css
.tabs-body {
  overflow-x: hidden;
  overflow-y: auto;
}
```

试试这个吧，做的时候没有考虑到内部滚动的场景。
